 
 <ul class="sidebar-menu">
        <?php foreach ($this->container as $page):
            /** @var Zend\Navigation\Page\AbstractPage $page */ ?>
            <li class="treeview">
            <a href="#">                              
                <i class="<?php echo $page->getClass();?>"></i><span> <?php echo $page->getLabel();?> </span>  
                 <span class="pull-right-container">
                 <i class="fa fa-angle-left pull-right"></i>
                 </span>        
            </a>
            <?php if ($page->hasPages()): ?>
                <ul class="treeview-menu">
                    <?php foreach ($page->getPages() as $child):
                        /** @var Zend\Navigation\Page\AbstractPage $child */ ?>
                        <li>
                            <a href="<?php echo $child->getHref() ?>"> <?php echo $child->getLabel()?> </a>                            
                        </li>
                    <?php endforeach; ?>
                </ul>
            <?php endif; ?>
            </li>
        <?php endforeach; ?>
    </ul>