<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'Calendar\Module'                        => __DIR__ . '/Module.php',
    'Calendar\Controller\CalendarController' => __DIR__ . '/src/Calendar/Controller/CalendarController.php',
    'CalendarTest\Framework\TestCase'        => __DIR__ . '/tests/Calendar/Framework/TestCase.php',
    'CalendarTest\SampleTest'                => __DIR__ . '/tests/Calendar/SampleTest.php',
);
