<!DOCTYPE html>

       
      <!-- Start page Label Plugins 
         =====================================================================-->
      <!-- fullcalendar css -->
      <link href="assets/plugins/fullcalendar/fullcalendar.min.css" rel="stylesheet" type="text/css"/>
      <!-- fullcalendar print css -->
      <link href="assets/plugins/fullcalendar/fullcalendar.print.min.css" rel="stylesheet" media='print' type="text/css"/>
      <!-- End page Label Plugins 
         =====================================================================-->
      <!-- Start Theme Layout Style
         =====================================================================-->
      <!-- Theme style -->
      <link href="assets/dist/css/stylecrm.css" rel="stylesheet" type="text/css"/>
      <!-- Theme style rtl -->
      <!--<link href="assets/dist/css/stylecrm-rtl.css" rel="stylesheet" type="text/css"/>-->
      <!-- End Theme Layout Style
         =====================================================================--
         <!-- =============================================== -->
         <!-- Content Wrapper. Contains page content -->
         
            <!-- Content Header (Page header) -->
            <section class="content-header">
               <div class="header-icon"><i class="fa fa-calendar-o"></i></div>
               <div class="header-title">
                  <h1>Calender</h1>
                  <small>Show Events</small>
               </div>
            </section>
            <!-- Main content -->
            <section class="content">
               <div class="row">
                  <div class="col-sm-12 col-md-3">
                     <div class="panel panel-bd">
                        <div class="panel-body">
                           <div id='external-events'>
                              <h4>Draggable Events</h4>
                              <div class='fc-event'>Riunione</div>
                              <div class='fc-event'>Permesso</div>
                              <div class='fc-event'>Ferie</div>
                              <div class='fc-event'>Malattia</div>
                              <div class='fc-event'>Pranzo di Lavoro</div>
                              <p>
                                 <input type='checkbox' id='drop-remove' />
                                 <label for='drop-remove'>remove after drop</label>
                              </p>
                           </div>
                        </div>
                     </div>
                     <div class="panel panel-bd">
                        <div class="panel-body">
                           <h4 class="m-t-0">FullCalendar</h4>
                           <p> is a jQuery plugin that provides a full-sized, drag &amp; drop calendar like the one below. It uses AJAX to fetch events on-the-fly for each month and is
                              easily configured to use your own feed format (an extension is provided for Google Calendar).
                           </p>
                           <p><a href="#" target="_blank">FullCalendar documentation</a></p>
                        </div>
                     </div>
                  </div>
                  <div class="col-sm-12 col-md-9">
                     <div class="panel panel-bd">
                        <div class="panel-body">
                           <!-- calender -->
                           <div id='calendar'></div>
                        </div>
                     </div>
                  </div>
               </div>
               
               <div id="calendarModal" class="modal fade">
		<div class="modal-dialog">
			<div class="modal-content">
				<div class="modal-header">
					<button type="button" class="close" data-dismiss="modal">&times;</button>
					<h4 class="modal-title">Event Details</h4>
				</div>
				<div id="modalBody" class="modal-body">
				      <input id="modalTitle" class="form-control" type="text" name="fname" ><br>
<!-- 					<h4 id="modalTitle" class="modal-title"></h4>  -->
					<div id="modalWhen" style="margin-top:5px;"></div>
				</div>
				<input type="hidden" id="eventID"/>
				<div class="modal-footer">
					<button class="btn" data-dismiss="modal" aria-hidden="true">Cancel</button>
					<button type="submit" class="btn btn-danger" id="deleteButton">Delete</button>
					<button type="submit" class="btn btn-primary" id="updateButton">Save</button>
				</div>
			</div>
		</div>
	</div>
	<div id="createEventModal" class="modal fade" role="dialog">
		<div class="modal-dialog">

			<!-- Modal content-->
			<div class="modal-content">
				<div class="modal-header">
					<button type="button" class="close" data-dismiss="modal">&times;</button>
					<h4 class="modal-title">Add Event</h4>
				</div>
				<div class="modal-body">
					<div class="control-group">
						<label class="control-label" for="inputPatient">Event:</label>
						<div class="field desc">
							<input class="form-control" id="title" name="title" placeholder="Event" type="text" value="">
						</div>
					</div>

					<input type="hidden" id="startTime"/>
					<input type="hidden" id="endTime"/>

					<div class="control-group">
						<label class="control-label" for="when">When:</label>
						<div class="controls controls-row" id="when" style="margin-top:5px;">
						</div>
					</div>

				</div>
				<div class="modal-footer">
					<button class="btn" data-dismiss="modal" aria-hidden="true">Cancel</button>
					<button type="submit" class="btn btn-primary" id="submitButton">Save</button>
				</div>
			</div>

		</div>
	</div>
            </section>
            
  
            <!-- /.content -->
      
        
   
      <!-- ./wrapper -->
      <!-- Start Core Plugins
         =====================================================================-->
      <!-- jQuery -->
      <script src="assets/plugins/jQuery/jquery-1.12.4.min.js" type="text/javascript"></script>
      <!-- jquery-ui --> 
      <script src="assets/plugins/jquery-ui-1.12.1/jquery-ui.min.js" type="text/javascript"></script>
      <!-- Bootstrap -->
      <script src="assets/bootstrap/js/bootstrap.min.js" type="text/javascript"></script>
      <!-- lobipanel -->
      <script src="assets/plugins/lobipanel/lobipanel.min.js" type="text/javascript"></script>
      <!-- Pace js -->
      <script src="assets/plugins/pace/pace.min.js" type="text/javascript"></script>
      <!-- SlimScroll -->
      <script src="assets/plugins/slimScroll/jquery.slimscroll.min.js" type="text/javascript"></script>
      <!-- FastClick -->
      <script src="assets/plugins/fastclick/fastclick.min.js" type="text/javascript"></script>
      <!-- CRMadmin frame -->
      <script src="assets/dist/js/custom.js" type="text/javascript"></script>
      <!-- End Core Plugins
         =====================================================================-->
      <!-- Start Page Lavel Plugins
         =====================================================================-->
      <!-- fullcalendar js -->

      <script src="assets/plugins/fullcalendar/lib/moment.min.js" type="text/javascript"></script>
      <script src="assets/plugins/fullcalendar/fullcalendar.min.js" type="text/javascript"></script>
      <script src="assets/plugins/fullcalendar/fullcalendar.js" type="text/javascript"></script>
      <!-- End Page Lavel Plugins
         =====================================================================-->
      <!-- Start Theme label Script
         =====================================================================-->
      <!-- Dashboard js -->
      <script src="assets/dist/js/dashboard.js" type="text/javascript"></script>
      <!-- End Theme label Script
         =====================================================================-->
      <script>
     
      
      function calndr() {    
    	  var calender = $('#calendar');
         /* initialize the external events
          -----------------------------------------------------------------*/
           var calndr = $('#external-events .fc-event');
         
           $(calndr).each(function () {
               
             // store data so the calendar knows to render an event upon drop       	  
             $(this).data('event', {               
                 title: $.trim($(this).text()), // use the element's text as the event title
                 start: $.trim('17:30'),
                 end:  $.trim('19:30'),
                 stick: true // maintain when user navigates (see docs on the renderEvent method)
             });
         
             // make the event draggable using jQuery UI
             $(this).draggable({
                 zIndex: 999,
                 revert: true, // will cause the event to go back to its
                 revertDuration: 0  //  original position after the drag
             });
         
         });
         
         /* initialize the calendar
          -----------------------------------------------------------------*/
         
         $(calender).fullCalendar({

        	 //FUNZIONE CHIAMATA QUANDO MODIFICO L'EVENTO
        	 eventResize: function(event) {
            	
                 
//                  $.ajax({
//                      url: 'home.php',
//                      data: 'action=update&title='+event.title+'&start='+moment(event.start).format()+'&end='+moment(event.end).format()+'&id='+event.id,
//                      type: "POST",
//                      success: function(json) {
//                          //alert(json);
//                      }
//                  });
             },
        	 //FUNZIONE CHIAMATA QUANDO MUOVO L'EVENTO
        	 eventDrop: function(event, delta){
            	 
//                  $.ajax({
//                      url: 'home.php',
//                      data: 'action=update&title='+event.title+'&start='+moment(event.start).format()+'&end='+moment(event.end).format()+'&id='+event.id ,
//                      type: "POST",
//                      success: function(json) {
//                      //alert(json);
//                      }
//                  });
             },
             select: function(start, end, jsEvent) {
                 endtime = end.format('h:mm');
                 starttime = start.format('dddd, MMMM Do YYYY, h:mm');
                 var mywhen = starttime + ' - ' + endtime;
                 start = start.format();
                 end = end.format();
                 $('#createEventModal #startTime').val(start);
                 $('#createEventModal #endTime').val(end);
                 $('#createEventModal #when').text(mywhen);
                 $('#createEventModal').modal('toggle');
            },
             //FUNZIONE CHIAMATO QUANDO CLICCO SULL'EVENTO
             eventClick:  function(event, jsEvent, view) {
            	 
            	 starttime = event.start.format('dddd, MMMM Do YYYY, h:mm');
            	 
                 endtime = event.end.format('h:mm');
                                  
                 var mywhen = starttime + ' - ' + endtime;
                 $('#modalTitle').val(event.title);
                 $('#modalWhen').text(mywhen);
                 $('#eventID').val(event.id);
                 $('#calendarModal').modal();
             },
      	   
             header: {
                 left: 'prev,next today',
                 center: 'title',
                 right: 'month,agendaWeek,agendaDay,listMonth'
             },
             defaultDate: '<?php echo date("Y-m-d")?>',
             slotDuration: '00:10:00',
             navLinks: true, // can click day/week names to navigate views
             businessHours: true, // display business hours
             editable: true,
             selectable: true,
             allDaySlot: false,
             droppable: true, // this allows things to be dropped onto the calendar
             drop: function () {
                    
                 // is the "remove after drop" checkbox checked?
                 if ($('#drop-remove').is(':checked')) {
                     // if so, remove the element from the "Draggable Events" list
                     $(this).remove();
                 }
             },
             events: [
            	 {
                     title: 'Pranzo di lavoro',
                     start: '<?php echo date("Y-m-d")?>T13:00:00',
                     end: '<?php echo date("Y-m-d")?>T15:00:00',
                     constraint: 'businessHours'
                 },
                 {
                     title: 'Business Lunch',
                     start: '2016-12-03T13:00:00',
                     constraint: 'businessHours'
                 },
                 {
                     title: 'Meeting',
                     start: '2016-12-13T11:00:00',
                     constraint: 'availableForMeeting', // defined below
                     color: '#009688'
                 },
                 {
                     title: 'Conference',
                     start: '2016-12-18',
                     end: '2016-12-20'
                 },
                 {
                     title: 'Party',
                     start: '2016-12-29T20:00:00'
                 },
                 // areas where "Meeting" must be dropped
                 {
                     id: 'availableForMeeting',
                     start: '2016-12-11T10:00:00',
                     end: '2016-12-11T16:00:00',
                     rendering: 'background'
                 },
                 {
                     id: 'availableForMeeting',
                     start: '2016-12-13T10:00:00',
                     end: '2016-12-13T16:00:00',
                     rendering: 'background'
                 },
                 // red areas where no events can be dropped
                 {
                     start: '2016-12-24',
                     end: '2016-12-28',
                     overlap: false,
                     rendering: 'background',
                     color: '#ff9f89'
                 },
                 {
                     start: '2016-12-06',
                     end: '2016-12-08',
                     overlap: false,
                     rendering: 'background',
                     color: '#ff9f89'
                 }
             ]
         });

         $('#submitButton').on('click', function(e){
             
             // We don't want this to act as a link so cancel the link action
             e.preventDefault();
             doSubmit();
         });
         
         $('#deleteButton').on('click', function(e){
             // We don't want this to act as a link so cancel the link action
             e.preventDefault();
             doDelete();
         });
         function doSubmit(){ 
          	  $("#createEventModal").modal('hide');
                var title = $('#title').val();
                var startTime = $('#startTime').val();
                var endTime = $('#endTime').val();
                
         
                $('#calendar').fullCalendar('renderEvent',
                        {
                            id: Math.floor(Math.random() * 100000),
                            title: title,
                            start: startTime,
                            end:  endTime,
                        },
                        true);

      }
         function doDelete(){
             $("#calendarModal").modal('hide');
             var eventID = $('#eventID').val();
alert(eventID);
                          $("#calendar").fullCalendar('removeEvents',eventID);

         }
  }
     
      
          

         calndr();
      
      </script>
  



